name: trademl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.5.0
  - numpy>=1.21.0
  - requests>=2.28.0
  - pyarrow>=10.0.0
  - scipy>=1.9.0
  - statsmodels>=0.13.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - jupyter
  - ipykernel
  - pip
  - tqdm>=4.64.0
  - pip:
    - arch>=5.3.0 